SellIt/Controllers/Admin/AdminController.cs
namespace SellIt.Controllers.Admin
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SellIt.Core.Constants;
    using SellIt.Core.Contracts.Admin;
    using SellIt.Core.ViewModels.Admin;

    [Authorize(Roles = UserConstants.Role.Administrator)]
    public class AdminController : Controller
    {
        private readonly IAdminService adminService;

        public AdminController(IAdminService adminService)
        {
            this.adminService = adminService;
        }

        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleViewModel role)
        {
            if (!ModelState.IsValid)
            {
                return View(role);
            }
            await adminService.CreateRoleAsync(role);

            return Redirect("/");
        }

        public async Task<IActionResult> AllUsers()
        {
            return View(await adminService.AllUsersAsync());
        }

        public async Task<IActionResult> SetRole()
        {
            var roles = await adminService.GetAllRolesAsync();
            ViewData["roles"] = roles.Select(s => new RoleViewModel
            {
                Name = s.Name,
            }).ToList();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SetRole(string userId, AllUsersViewModel all)
        {
            return await adminService.SetRoleAsync(userId, all)
                             .ContinueWith(_ => RedirectToAction("UserById", new { userId = all.UserId }));
        }

        public async Task<IActionResult> DeleteUser(string userId)
        {
            return await adminService.DeleteUserAsync(userId)
                             .ContinueWith(_ => RedirectToAction("AllUsers"));
        }

        public async Task<IActionResult> UserById(string userId)
        {
            return View(await adminService.UserByIdAsync(userId));
        }

        public async Task<IActionResult> UserProducts(string userId)
        {
            return View(await adminService.UserProductsAsync(userId));
        }
    }
}

SellIt/Controllers/Category/CategoryController.cs
namespace SellIt.Controllers.Category
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SellIt.Core.Constants;
    using SellIt.Core.Contracts.Category;
    using SellIt.Core.ViewModels.Category;

    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        [Authorize(Roles = UserConstants.Role.Administrator)]
        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = UserConstants.Role.Administrator)]
        public async Task<IActionResult> CreateCategory(CreateCategoryViewModel create)
        {
            if (!ModelState.IsValid)
            {
                return View(create);
            }

            try
            {
                await categoryService.CreateCategoryAsync(create);
                return Redirect("/");
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("Image", ex.Message);
                return View(create);
            }
        }
    }
}

SellIt/Controllers/ForAprooved/ForAproovedController.cs
namespace SellIt.Controllers.ForAprooved
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SellIt.Core.Constants;
    using SellIt.Core.Contracts.ForAprooved;

    public class ForAproovedController : Controller
    {
        private readonly IForAproovedService aproovedService;

        public ForAproovedController(IForAproovedService aproovedService)
        {
            this.aproovedService = aproovedService;
        }

        [Authorize(Roles = UserConstants.Role.Administrator)]
        public async Task<IActionResult> GetAllProductsForAproove()
        {
            return View(await aproovedService.GetAllProductsForAprooveAsync());
        }

        [Authorize(Roles = UserConstants.Role.Administrator)]
        public async Task<IActionResult> SetAproove(int id)
        {
            return await aproovedService.SetAprooveAsync(id)
             .ContinueWith(_ => Redirect("/"));
        }
    }
}

SellIt/Controllers/Message/MessageController.cs
namespace SellIt.Controllers.Message
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SellIt.Core.Constants;
    using SellIt.Core.Contracts.Admin;
    using SellIt.Core.Contracts.Messages;
    using SellIt.Core.Contracts.User;

    public class MessageController : Controller
    {
        private readonly IMessagesService messagesService;
        private readonly IAdminService adminService;
        private readonly string UserName;

        public MessageController(IMessagesService messagesService, IAdminService adminService)
        {
            this.messagesService = messagesService;
            UserName = adminService.CurrentUserName();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SendMessage(int id, string message)
        {
            return !string.IsNullOrEmpty(message)
             ? await messagesService.SendMessageAsync(UserName, id, message)
             .ContinueWith(_ => Json(new { success = true }))
             : await Task.FromResult(Json(new { success = false, message = MessageConstants.EmptyMessage }));
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ReplyMessage(string replyMessage, int id)
        {
            return !string.IsNullOrEmpty(replyMessage)
               ? await messagesService.ReplyMessageAsync(UserName, replyMessage, id)
               .ContinueWith(_ => Json(new { success = true }))
               : await Task.FromResult(Json(new { success = false, message = MessageConstants.EmptyMessage }));
        }

        [Authorize]
        public async Task<IActionResult> AllProductMessages(int id)
        {
            return View(await messagesService.AllProductMessagesAsync(id));
        }

        [Authorize]
        public async Task<IActionResult> AllMessages()
        {
            return View(await messagesService.AllMessagesAsync());
        }

        [Authorize]
        public async Task<IActionResult> GetProductMessageById(int id)
        {
            return View(await messagesService.GetProductMessageByIdAsync(id));
        }
    }
}

SellIt/Controllers/User/UserController.cs
namespace SellIt.Controllers.User
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SellIt.Core.Contracts.User;
    using SellIt.Infrastructure.Data.Models;

    public class UserController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IUserService userService;

        public UserController(IUserService userService, UserManager<User> userManager)
        {
            this.userService = userService;
            this.userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> MyProducts()
        {
            return View(await userService.MyProductsAsync(userManager.GetUserId(User)));
        }
    }
}

SellIt/Views/Shared/ByIdSharedOld.cshtml
@using SellIt.Core.ViewModels.Product
@model GetByIdAndLikeViewModel




@if (Model.IsAprooved == true)
{
    <a class="btn btn-app bg-success">
        <span class="badge bg-purple">@Model.Viewed</span>
        <i class="fas fa-users"></i> Viewed
    </a>

    @if (User.Identity.IsAuthenticated)
    {
        <btn id="likeButton" class="btn btn-app bg-cyan" asp-route-id="@Model.Id">
            <span id="liked" class="badge bg-danger">@Model.LikedCount</span>
            <i class="fas fa-heart"></i> Likes
        </btn>
    }
}

<div class="col-md-4">
    <ul class="list-group">
        <li class="list-group-item">@Model.Name</li>
    </ul>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">

            @for (int i = 0; i < Model.Gallery.Count(); i++)
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i==0 ? "active" : "") "></li>
            }
        </ol>
        <div class="carousel-inner">
            @for (int i = 0; i < Model.Gallery.Count(); i++)
            {
                <div class="@(i==0 ? "carousel-item active" : "carousel-item") ">
                    <a href="@Model.Gallery[i].URL">
                        <img class="d-block w-100" src="@Model.Gallery[i].URL" alt="@Model.Gallery[i].Name">
                    </a>
                </div>
            }

        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
        <ul class="list-group">
            <li class="list-group-item">Category: @Model.CategoryName</li>
            <li class="list-group-item">@Model.Description</li>
            <li class="list-group-item">@Model.Price $</li>
            <li class="list-group-item">@Model.ProducAddress</li>
            <li class="list-group-item">@this.ViewData["address"]</li>
        </ul>
    </div>
    <hr />

    @if (User.Identity.Name != Model.UserName)
    {
        <a id="sendMessageButton" asp-route-id="@Model.Id" class="btn btn-success">Send Message</a>
    }
</div>


@if (Model.IsAprooved == false)
{
    <h5 style="color:red">The item is checking </h5>
}


@if (User.IsInRole("Administrator"))
{
    @if (Model.IsAprooved == false)
    {
        <a asp-action="SetAproove" asp-controller="ForAprooved" asp-route-id="@Model.Id" class="btn btn-success">Aproove item</a>
    }
}

<div id="contentContainer"></div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    let likedElement = $("#liked");
    let likeButton = $("#likeButton");
    let modelId = @Model.Id;
    let modelCount = @Model.LikedCount;

    likeButton.on("click", function(event) {
        event.preventDefault();

        let currentLikedCount = parseInt(likedElement.text());
        let newLikedCount = currentLikedCount + 1;

        $.ajax({
            url: `/Product/Like?id=${modelId}`,
            type: "POST",
            contentType: "application/json",
            data: JSON.stringify({ likedCount: newLikedCount }),
            success: function(response) {
                location.reload();
            },
            error: function(xhr, status, error) {
                console.log("An error occurred:", error);
            }
        });
    });
</script>


<script>
    let sendMessageButton = $("#sendMessageButton");
    sendMessageButton.on("click", function(event) {
        event.preventDefault();
        let inputElement = $('<input type="text" id="textInput">');
        let sendButton = $('<button id="sendButton">Send</button>');
        $('#contentContainer').empty().append(inputElement).append(sendButton);
        sendButton.on("click", function () {
            let inputValue = $('#textInput').val();
           
                $.ajax({
                    url: `/Message/SendMessage`,
                    type: "POST",
                    data: { id: modelId, message: inputValue },
                    success: function (response) {
                        window.location.href = '/';
                    },
                    error: function (xhr, status, error) {
                        console.log("An error occurred:", error);
                    }
                });        
        });
    });
</script>
    
  

  

SellIt/Views/Shared/_Layout.cshtml
@using SellIt.Core.Constants
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SellIt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SellIt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SellIt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                           @if (User.IsInRole(UserConstants.Role.Administrator))
                                {
                                <a class="nav-link" asp-action="CreateCategory" asp-controller="Category">Create Category</a>
                                <a class="nav-link" asp-action="CreateRole" asp-controller="Admin">Create Role</a>
                                <a class="nav-link" asp-action="AllUsers" asp-controller="Admin">All Users</a>
                                <a class="nav-link" asp-action="AllProducts" asp-controller="Product">All Products</a>
                                <a class="nav-link" asp-action="GetAllProductsForAproove" asp-controller="ForAprooved">All Products For Aprooved</a>
                                }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now - SellIt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SellIt/Views/Shared/_MainMenu.cshtml
@using SellIt.Core.Constants
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        @* <li class="nav-item menu-open">
        <a href="#" class="nav-link active">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
        Starter Pages
        <i class="right fas fa-angle-left"></i>
        </p>
        </a>
        <ul class="nav nav-treeview">
        <li class="nav-item">
        <a href="#" class="nav-link active">
        <i class="far fa-circle nav-icon"></i>
        <p>Active Page</p>
        </a>
        </li>
        <li class="nav-item">
        <a href="#" class="nav-link">
        <i class="far fa-circle nav-icon"></i>
        <p>Inactive Page</p>
        </a>
        </li>
        </ul>
        </li>*@
        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
                <a class="navbar-brand" asp-action="MyProducts" asp-controller="User"><i class="nav-icon fas fa-th"> My Products</i></a>
            </li>
                <a class="navbar-brand" asp-action="Favorites" asp-controller="Product"><i class="nav-icon fas fa-th"> Favorites</i></a>
            <a class="navbar-brand" asp-action="AddProduct" asp-controller="Product">Add Product</a>
        }
        @if (User.IsInRole(UserConstants.Role.Administrator))
        {
            <a class="navbar-brand" asp-action="CreateCategory" asp-controller="Category">Create Category</a>
            <a class="navbar-brand" asp-action="CreateRole" asp-controller="User">Create Role</a>
            <a class="navbar-brand" asp-action="AllUsers" asp-controller="User">All Users</a>
            <a class="navbar-brand" asp-action="AllProducts" asp-controller="Product">All Products</a>
            <a class="navbar-brand" asp-action="GetAllProductsForAproove" asp-controller="ForAprooved">All Products For Aprooved</a>
        }
    </ul>
</nav>

SellIt/Views/Shared/_Message.cshtml
@using SellIt.Core.Constants

@if (ViewData[MessageConstants.ErrorMessage] != null)
{
    <script>
        $(function () {
            toastr.error('@ViewData[MessageConstants.ErrorMessage]?.ToString()');
        });
    </script>
}

@if (ViewData[MessageConstants.WarningMessage] != null)
{
    <script>
        $(function () {
            toastr.warning('@ViewData[MessageConstants.WarningMessage]?.ToString()');
        });
    </script>
}

@if (ViewData[MessageConstants.SuccessMessage] != null)
{
    <script>
        $(function () {
            toastr.success('@ViewData[MessageConstants.SuccessMessage]?.ToString()');
        });
    </script>
}